# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensajes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaccion_tiempo', models.DateTimeField(verbose_name='Tiempo de transaccion')),
                ('transaccion_modo', models.BinaryField(verbose_name=['Envio', 'Recepcion'])),
                ('can_timestamp', models.FloatField(verbose_name='CAN - Marcaje de Tiempo')),
                ('can_is_remote_frame', models.BooleanField(verbose_name='CAN - Frame Remoto')),
                ('can_extended_id', models.BooleanField(verbose_name='CAN - ID Extendido')),
                ('can_is_error_frame', models.BooleanField(verbose_name='CAN - Frame de Error')),
                ('can_arbitration_id', models.IntegerField(verbose_name='CAN - ID Mensaje')),
                ('can_dlc', models.IntegerField(verbose_name='CAN - DLC')),
                ('can_data', models.CharField(max_length=200)),
            ],
        ),
    ]
