# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20171111_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajes',
            name='can_data',
            field=models.CharField(max_length=200, verbose_name='CAN - Dato'),
        ),
        migrations.AlterField(
            model_name='mensajes',
            name='transaccion_modo',
            field=models.CharField(choices=[('ENVIAR', 'Envio'), ('RECIBIR', 'Recepcion')], max_length=200, verbose_name='Modo de transaccion'),
        ),
    ]
