# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20171111_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='can_dlc',
            field=models.IntegerField(blank=True, verbose_name='CAN - DLC'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='can_extended_id',
            field=models.BooleanField(default=False, verbose_name='CAN - ID Extendido'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='can_is_error_frame',
            field=models.BooleanField(default=False, verbose_name='CAN - Frame de Error'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='can_is_remote_frame',
            field=models.BooleanField(default=False, verbose_name='CAN - Frame Remoto'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='can_timestamp',
            field=models.FloatField(blank=True, verbose_name='CAN - Marcaje de Tiempo'),
        ),
    ]
