# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20171111_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='can_dlc',
            field=models.IntegerField(null=True, verbose_name='CAN - DLC'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='can_timestamp',
            field=models.FloatField(null=True, verbose_name='CAN - Marcaje de Tiempo'),
        ),
    ]
