# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20171111_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='can_arbitration_id',
            field=models.CharField(max_length=10, verbose_name='CAN - ID Mensaje'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='can_extended_id',
            field=models.BooleanField(default=True, verbose_name='CAN - ID Extendido'),
        ),
    ]
